name: Build and Test

on:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10, 12]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project
        working-directory: ./frontend
        run: npm install

      - name: Build the project
        working-directory: ./frontend
        run: npm run build --if-present

      - name: Run tests
        working-directory: ./frontend
        run: npm test

      - name: Check project
        working-directory: ./frontend
        run: npm run check --if-present
